[package]
name = "symchat"
version = "1.0.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.11"
clap = { version = "4", features = ["derive"] }
hmac = "0.12"
pbkdf2 = "0.10"
rand = "0.8"
sha2 = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"

